from os import path
from codecs import open
from setuptools import setup, find_packages

here = path.abspath(path.dirname(__file__))
with open(path.join(here, "README.md"), encoding="utf-8") as f:
    long_description = f.read()

AUTHOR = "Ariel Ladegaard"
URL = "https://github.com/ExoMars-PanCam/passthrough"

pkg_info_template = f"""\
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__author__ = '{AUTHOR}'
__homepage__ = '{URL}'
__version__ = '{{version}}'
"""

setup(
    name="passthrough",
    use_scm_version={
        "write_to": "src/passthrough/_pkg_info.py",
        "write_to_template": pkg_info_template,
    },
    description="Passthrough - PDS4 label template system",
    long_description=long_description,
    url=URL,
    packages=find_packages("src"),
    package_dir={"": "src"},
    include_package_data=True,
    author=AUTHOR,
    author_email="arl13@aber.ac.uk",
    license="MIT",
    classifiers=[
        # TODO: change as appropriate
        "Development Status :: 3 - Alpha",
        "Environment :: Console",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: POSIX :: Linux",
        "Programming Language :: Python :: 3 :: Only",
        "Topic :: Scientific/Engineering :: Physics",
    ],
    keywords="file directory watcher clipboard",
    setup_requires=[
        "setuptools_scm>=1.7",
    ],
    install_requires=[
        "lxml",
        # "numpy>=1.14",
        # "pds4-tools>=1.1",
    ],
    # tests_requires=[
    #     "tox>=3.1.2",
    #     "pytest>=3.5",
    # ],
    # extras_require={
    #     'coloredlogs': ["coloredlogs>=9.0"],
    # },
    entry_points={
        "console_scripts": [
            # "ptvalidate=passthrough.scripts.ptvalidate:cli",
            "pttesting=passthrough.testing.pttesting:cli",
        ],
    },
    python_requires=">=3.6",
)
